version: '3'

networks:
  laravel:

services:
  web_app_strive:
    build:
      context: .
      dockerfile: Dockerfile
    image: features_strivers
    container_name: web_strive
    ports:
      - "9000:8000"
    volumes:
      - .:/var/www/html
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  # mysql:
  #   image: mysql:5.7.29
  #   container_name: mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: dbs_db_t
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: r
  #     MYSQL_ROOT_PASSWORD: r
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #   networks:
  #     - laravel

#   mysql_strive:
#     image: mysql:5.7
#     container_name: mysql_server_strive
#     restart: unless-stopped
#     tty: true
#     # ports:
#     #   - "3306:3306"
#     environment:
#       MYSQL_DATABASE: strive
#       #MYSQL_USER: root
#       MYSQL_PASSWORD: strive
#       MYSQL_ROOT_PASSWORD: strive
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql_server_strive
#     volumes:
#       - dbdata:/var/lib/mysql/
#     networks:
#       - laravel
  
#   # phpmyadmin
#   phpmyadmin:
#     depends_on:
#       - mysql_strive
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - '8080:80'
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: password
#       UPLOAD_LIMIT: 300M
#     networks:
#       - laravel    

# volumes:
#   dbdata:
#     driver: local